### PR TITLE
Allow getMemberValuePath to get data from a TaggedTemplateExpression

### PR DESCRIPTION
**Pull request by Jmeyering**
This will enable additional tooling like styled-components and diet-cola to create components which get 'picked up' by react-docgen.

Addresses #187

### CODE REVIEW

**Comment by fkling** [comment]
Thank for this! I think this is fine overall, but please add a test.

It might also be worth to add a comment why this was added and maybe add a link to your resolver.

Once this all works together, we should list your resolver somewhere, maybe in the wiki.

**Comment by Jmeyering** [comment]
Any direction on how to add a test? The test suite by default uses the built in resolvers, which do not include tagged template literals.

I don't see any place where I can unit test the individual methods that I changed. I will gladly add a comment to my changes.

**Comment by Jmeyering** [comment]
@fkling 

A couple things

1. I checked `react-styleguidist` and it looks as though they are locked to v3-dev for their dep on `react-docgen` As that is the primary use case that I am aware of at this time, I have made a new PR for the `v3-dev` branch #198. Should we close this PR and only work on this as a v3-dev feature?
2. I've added inline documentation for my changes in #198.
3. Testing is still confusing me a bit. Any direction would be greatly appreciated

**Comment by Jmeyering** [comment]
@fkling Is there any one who could provide some direction on getting testing implemented? As I've commented before it doesn't seem to me that there are any unit tests explicitly covering the methods that I have altered.  Fixtures are used to test most of the functionality of react-docgen. But as the library itself does not have any way to resolve a TaggedTemplateLiteral as a component, I'm a bit stuck. 

Thanks so much for your time.

**Comment by fkling** [comment]
Sorry for letting this sit for so long (I also was away in between)....

Regarding testing, you could start by adding tests to `getMemberExpressionValuePath-test.js` and `getMemberValuePath-test.js`. Something like

```js
 describe('TaggedTemplateLiteral', () => {
    it('finds "normal" property definitions', () => {
      var def = statement(`
        var Foo = foo\`bar\`
        Foo.propTypes = {};
      `);

      expect(getMemberExpressionValuePath(def, 'propTypes'))
        .toBe(def.parent.get('body', 1, 'expression', 'right'));
    });
});
```

and

```js
  it('handles TaggedTemplateLiterals', () => {
    var path = expression('foo``');

    getMemberValuePath(path, 'foo');
    expect(getPropertyValuePath).toBeCalledWith(path, 'foo');
  });
```

**Comment by Jmeyering** [comment]
Closing this as it's merged into v3-dev

**Pull request closed without merging**
