### PR TITLE
v3-dev Allow getMemberValuePath to get data from a TaggedTemplateExpression

### PR DESCRIPTION
**Pull request by Jmeyering**
Adding the same functionality to v3 as proposed in.

https://github.com/reactjs/react-docgen/pull/195

### CODE REVIEW

**Comment by Jmeyering** [comment]
@fkling 

I added the test into this PR. I think we can drop the PR into master and keep this a v3 feature?

Let me know if there is anything I can improve upon.

**Comment by Jmeyering** [comment]
@fkling 
Let me know if there is anything else I can do to move this along. If the tests aren't up to spec I'm willing to do more to get this acceptable.

**Comment by sapegin** [comment]
@fkling Could you please take a look at this?

**Comment by fkling** [comment]
Sorry for letting this sit for so long. This is great, thank you! 😃

**Pull request merged**
