### PR TITLE
useImperativeHandle support

### PR DESCRIPTION
**Pull request by mfazekas**
Rebase of #454 to current main

### CODE REVIEW

**Comment by danez** [comment]
Thanks for this and sorry for the delay. I haven't had time to review this.

It will take a little bit once I find time.

**Comment by naftalibeder** [comment]
Just want to bump this, in case there's any chance of getting this merged soon. Thanks!

**Comment by mfazekas** [comment]
@danez rebased again

**Comment by mfazekas** [comment]
@denez rebased again

**Pull request closed without merging**
