### PR TITLE
Use Flow's parser instead of babylon

### PR DESCRIPTION
**Pull request by wbinnssmith**
This switches react-docgen's parser to the Flow parser, ensuring better
compatibility with the JavaScript flow can parse. react-docgen was
previously limited to whatever Babel 5 could parse.

Current caveats:
 * Flow's parser currently [incorrectly parses decorators](https://github.com/facebook/flow/issues/2741),
   leading to a host of workarounds in the jsdoc docblock-finding code.
   Once the flow parser can correctly consider these decorators and
   include the "@" character in the decorator source rather than a free
   identifier, recast should be able to correctly attribute the docblock
   comment, letting us remove most, if not all of these hacks.
 * Also due to Flow's parsing of decorators as two identifiers, using
   a decorated class expression as an expression (valid JavaScript, see
   below) fails. This is a breaking change with current react-docgen
   behavior. We'll need to set the baseline for docgen as whatever Flow
   can correctly parse. Here's an example of valid JS that breaks in
   Flow:

   ```js
   myFunction(
     /**
     * My Docblock
     */
     @MyDecorator
     class MyClass extends React.Component {}
   )
   ```

Thanks for your help on this personally, @fkling!
Hopefully this opens up a whole new set of users of docgen :)

### CODE REVIEW

**Comment by fkling** [comment]
Thank you! This will fix #125 .

**Comment by wbinnssmith** [comment]
cc @mroch @gabelevi on the Flow issues, not sure how much a priority (arguably deprecated) decorators are, but I imagine that failing test case might help with facebook/flow#2741

**Comment by danez** [comment]
But with this we will loose the ability to parse early stage proposals, which babylon supports, so babylon 6 could be a valid alternative here.

**Comment by fkling** [comment]
Good point @danez, I haven't thought about that. However, babylon 6 deviates from the estree spec which also isn't great.

I'd be curious how much the early proposals are actually used.

**Comment by aaronjensen** [comment]
I wonder if going the route of eslint and having pluggable parsers is the right way. It's too bad we can't just have one 😄

**Comment by MoOx** [comment]
I am having issue with react-styleguidist when trying to make my files using this kind of syntax: `name?: value`. babylon fails on ?. But not sure why since for my app I don't have any issue and babylon parse this correctly as babel transforms this like a charm.

**Comment by danez** [comment]
@MoOx react-docgen is using babylon 5 which does not support newer flow features.

**Comment by MoOx** [comment]
Oh! Make sense then. Thanks for the comment :)

**Comment by danez** [comment]
What we were also discussing some time ago in the babel slack, if it would make sense to have an option to create estree compatible output (at least for stage-4 syntax). This could then at least help the effort to have exchangeable parsers in react-docgen and one of them being babylon6.

**Comment by fkling** [comment]
@danez Any update on that? I started looking into supporting both, babylon and flow, but it's a bit of work. Having babylon produce an estree compliant AST would certainly make this a lot easier 😉

**Comment by danez** [comment]
Yes I started on that already, but will need more time babel/babylon#277

**Comment by fkling** [comment]
@danez This looks certainly better than what I currently have to do to make react-docgen work. Thank you!

**Comment by jribeiro** [comment]
@danez I see the your feature babel/babylon#277 was merged but this PR is still opened. Do you know if this is this still an issue?

**Comment by danez** [comment]
Yes you can try install react-docgen v3.0.0-beta5 which includes the latest babylon version.

**Comment by jribeiro** [comment]
Great @danez, will do. Thanks a lot

**Comment by danez** [comment]
I close that for now, we can get back to this if we want to have exchangeable parsers.

**Pull request closed without merging**
