### PR TITLE
contextTypeHandler and childContextTypeHandler

### PR DESCRIPTION
**Pull request by coot**
Add two new handlers based on `handlers.propTypeHandler`.

### CODE REVIEW

**Comment by fkling** [comment]
Sorry for not commenting on this earlier. This seems reasonable to me, but could you please provide tests for the new handlers as well? Or at least a snapshot test in `src/__tests__/fixtures`? 
Thank you!

**Comment by andyearnshaw** [comment]
@coot are you planning on adding the tests @fkling asked for soon? I'd certainly appreciate having this functionality :smile:.

**Comment by coot** [comment]
@andyearnshaw - it might take me a while to do that, do you fancy adding them?

**Comment by andyearnshaw** [comment]
Sure! I will try to make time over the next week.

**Comment by danez** [comment]
Integrated in #260.

Thanks for your work.

**Pull request closed without merging**
