### PR TITLE
fix: type inference on forwardRef components

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
@danez any chance we could get this in swiftly and push a release? Happy to help on that front as well.

**Comment by danez** [comment]
Thanks, yeah I haven't been really active lately.

**Comment by jquense** [comment]
no worries we all get busy. If you feel comfortable with it, i'd be happy to share some of the merging and publishing duties!

**Comment by jquense** [comment]
@danez  friendly ping. It'd be great to get this into a release, and again i'd be happy to help maintain and manage that since it looks like you don't have enough time at the moment :)

**Pull request merged**
