### PR TITLE
Add checking stateless component default props

### PR DESCRIPTION
**Pull request by CompuIves**
Fixes https://github.com/reactjs/react-docgen/issues/69,

With this PR we first search for `defaultProps` of the stateless component (if stateless) and then check using `defaultProps` or `getDefaultProps`, it will overwrite the `defaultProps` of the stateless component if any is found.

Let me know what you think of it, this is my first time working with AST, so I'm prepared for all feedback 😅 .

### CODE REVIEW

**Comment by CompuIves** [comment]
Ah, I just read that it probably should in a seperate handler @fkling. If you still have this opinion I can move it to a seperate handler.

**Comment by sapegin** [comment]
@fkling Could you please review this pull request?

**Comment by fkling** [comment]
Yeah, I think this is good to go, just needs to be rebased.

**Comment by CompuIves** [comment]
Rebased!

**Comment by fkling** [comment]
Merged! Though I don't know when we are going to release a new version yet (I just released one, I guess I should have waited 😛  ).

**Comment by eisisig** [comment]
Any idea of a new version? I need this :)

**Comment by fkling** [comment]
I'll get something out within the next two days! (just came back from vacation)

**Comment by eisisig** [comment]
Looking forward to it! Hope you had a good one

**Pull request merged**
