### PR TITLE
feat(react): Support new flow 0.53 annotations

### LINKED ISSUE #207: Extracted flow 0.53 props from react component are not recognized
I have just changed our codebase to the new flow types for React (meaning to use stuff as described [here](https://flow.org/en/docs/react/components/#toc-class-components)).

So my react classes now look like that:

```javascript
type Props = {
    value: boolean,
};

class MyComponent extends React.Component<Props> {
    // ...
}
```

These props are then not recognized by the library anymore... I am using version 2.17.0.

### PR DESCRIPTION
**Pull request by danez**
Fixes #207

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Material-UI project is looking forward seeing this PR released.
@danez Thanks for working on it!

**Comment by danrot** [comment]
Thanks a lot! When will this be released?

**Comment by danez** [comment]
It is released now as 2.18.0

**Comment by rosskevin** [comment]
I'm trying out 2.18.0 on `material-ui/v1-beta` and it is still failing to parse the first file.  I'm trying to isolate where it is, but I do know it is falling through in the `flowParsePrimaryType`.  If others are having problems or finding quirks, please let us know.

I'll see if I can get an isolated test case figured out.

**Comment by danez** [comment]
Do you have an error? Or are the docs incorrect?

**Comment by oliviertassinari** [comment]
@rosskevin I have been applying the fix locally with success. (a week ago with flow 0.53 no 0.54).

**Comment by rosskevin** [comment]
I have an error, it is failing on a stateless function.  @oliviertassinari good to know, I'm using 2.18.0 release on the tip of v1-beta.

Looking at the package to see if the change made it.

**Comment by rosskevin** [comment]
This failure originates in babylon.  Versioning issue?

```javascript
$ rimraf pages/api/* && babel-node ./docs/scripts/buildApi.js
Error parsing src for /Users/kross/projects/material-ui/src/Avatar/Avatar.js
/Users/kross/projects/material-ui/docs/scripts/buildApi.js:87
    throw err;
    ^

SyntaxError: Unexpected token (53:21)
    at Parser.pp.raise (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.flowParsePrimaryType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:552:8)
    at Parser.pp.flowParsePostfixType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:557:38)
    at Parser.pp.flowParsePrefixType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:573:17)
    at Parser.pp.flowParseIntersectionType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:579:19)
    at Parser.pp.flowParseUnionType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:589:19)
    at Parser.pp.flowParseType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:600:19)
    at Parser.pp.flowParseTypeParameterInstantiation (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:217:27)
    at Parser.pp.flowParseGenericType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:364:32)
error Command failed with exit code 1.
```

```
yarn list babylon
yarn list v0.27.5
├─ babylon@6.18.0
├─ react-docgen@2.18.0
│  └─ babylon@5.8.38
└─ styled-jsx@1.0.10
   ├─ babel-traverse@6.21.0
   │  └─ babylon@6.18.0
   └─ babylon@6.14.1
```

**Comment by rosskevin** [comment]
Failure is on `children?: Element<*>`, I also have `component?: string | ComponentType<*>` but I commented it out on the hunch that the `Element` inference was breaking it.

**Comment by rosskevin** [comment]
I'm going to pull and add some [`children` test cases](https://flow.org/en/docs/react/children/) instead of working from the outside.

**Comment by danez** [comment]
Babylon 5 does not support `*`. You will want to use react-docgen v3-beta, but I haven't released a new version of react-docgen v3-beta with the flow-react fix yet as I had some test issues. I wanted to investigate later.

**Pull request merged**
