### PR TITLE
Update main-test.js

### PR DESCRIPTION
**Pull request by oliviertassinari**
Test that the evaluation is working for the defaultProps and not only propTypes.

### CODE REVIEW

**Comment by fkling** [comment]
Given that the test fails, it seems that `defaultProps` is not resolved to its value?

**Comment by oliviertassinari** [comment]
Exactly.

**Comment by donnieberg** [comment]
@fkling Thanks for brining this to their attention. I'm using ES6 classes and am experiencing the same problem with getting defaultProps documentation from my components.

**Comment by fkling** [comment]
I fixed the issue locally and simply changed the existing tests to use referenced propTypes and defaultProps, instead of adding your additional test.

I hope that's fine with you, thank you very much for noticing this issue!

**Pull request closed without merging**
