### PR TITLE
update jest to 14

### PR DESCRIPTION
**Pull request by NogsMPLS**
updated jest, ran `npm run test` and tests passed on my OSX machine, so from what I can tell no breaking changes for this repo.

### CODE REVIEW

**Comment by NogsMPLS** [comment]
Hopefully this also fixes https://github.com/reactjs/react-docgen/pull/59#issuecomment-236194249

🙏

**Comment by NogsMPLS** [comment]
😭 😭 😭 😭 

node 4 env failed, just like the other PRs

**Comment by fkling** [comment]
😞

**Comment by fkling** [comment]
I guess I'll have to investigate a bit 🔍  ...

**Comment by danez** [comment]
Dang didn't see there is already a PR for this (#106). Seems the tests on npm@2 sometimes fail, because they take too long. I was wondering if jest is maybe compiling the node_modules, but they should be ignored by default. So its probably babel that is slow and makes the worker crash/timeout.

**Comment by danez** [comment]
this was fixed with #106

**Pull request closed without merging**
