### PR TITLE
Fixed infinite loop in utils/isStatelessComponent.js

### PR DESCRIPTION
**Pull request by rtsao**
Parsing a file that contains anything like below will result in react-docgen hanging:

```jsx
export function foo() {
  return [].join();
}
```

I haven't had a chance to dig into this yet, but we've been bitten by this.

### CODE REVIEW

**Comment by rtsao** [comment]
The infinite loop occurs in this while expression: https://github.com/reactjs/react-docgen/blob/6f7368658ddda6f7cdb03d62c0a59b065bdd42fe/src/utils/isStatelessComponent.js#L95

I'll see if I can fix this

**Comment by rtsao** [comment]
I've added a really basic fix. I think array literal usage is the corner case here so a simple check should suffice. It doesn't seem to me a loop would occur in any other case.

**Comment by fkling** [comment]
Uh, thanks for that! I believe there are other cases whether this would be an issue, e.g.

```js
return {}.foo()
```

It seems like what this is doing is unrolling bested *MemberExpression*s. So maybe the loop condition should rather be

```js
while (calleeValue.get('object').node.type === 'MemberExpression')
```

?

cc @iamdustan who wrote this code. Maybe adding a comment about what exactly this does would be useful 😉

**Comment by iamdustan** [comment]
Hey, this was a long time ago :innocent:

I was out of town last week and only have a couple days around this week and next week; so it’ll probably be 3 weeks before I will have time to get my brain back into this for realsies.

**Comment by fkling** [comment]
@rtsao, what's the progress or your thoughts on this?

**Comment by rtsao** [comment]
I've been using my fork with this patch without any issue (I think call expressions with object literals is pretty rare).

I'd be happy to refactor this to make the fix more robust (maybe explore the alternate while condition described above) but probably won't get a chance to in the near term.

**Comment by iamdustan** [comment]
After looking through both of these a bit more I am pretty sure that PR #139 that @tchon just opened is the more robust fix to this.

**Comment by rtsao** [comment]
Agreed, closing in favor of https://github.com/reactjs/react-docgen/pull/139

**Pull request closed without merging**
